### ISSUE TITLE
OS X example_game crashes

### ISSUE THREAD

**Issue by forrestthewoods** [forrestthewoods/fts_remote_console#10]
Running example_game on OS X crashes with the following exception: "Cannot assign requested address". I don't have access to an OS X machine for development so I've not been able to fix it.

I believe the socket and/or endpoint in fts::udp::Broadcaster needs to be constructed with different params. Although I can't be certain.

https://github.com/forrestthewoods/fts_remote_console/blob/master/code/net/udp_broadcaster.cpp#L23

**Comment by pafmaf** [comment]
Works on OSX if you specify a port:

`asio::ip::udp::resolver::query query(asio::ip::udp::v4(), "google.com", "daytime");`

on line:

https://github.com/forrestthewoods/fts_remote_console/blob/04570e720e50c32de4237958437bb9ec3032a8d5/code/example_game/example_game_main.cpp#L55

**Comment by forrestthewoods** [comment]
That did the trick. Thank you very much!
